/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

export enum StatoDocumentoEnum {
  ACQUISITO = 'ACQUISITO',
  IN_ELABORAZIONE = 'IN_ELABORAZIONE',
  ERR_ACQUISIZIONE = 'ERR_ACQUISIZIONE',
  ERR_ANALISI = 'ERR_ANALISI',
  ERR_SBUSTAMENTO = 'ERR_SBUSTAMENTO',
  ELABORATO = 'ELABORATO'
}
