/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * acta.v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ClassificazioneActa { 
    id?: string;
    dataInizio?: string;
    dataFine?: string;
    legislatura?: string;
    numero?: string;
    stato?: string;
    codice?: string;
    cartaceo?: boolean;
    docAllegato?: boolean;
    docConAllegati?: boolean;
    copiaCartacea?: boolean;
}

