/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * firma.v1
 * API per la gestione della firma digitale
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoContenutoFirmato } from './tipoContenutoFirmato.d';
import { TipoFirma } from './tipoFirma.d';
import { EsitoVerificaFirma } from './esitoVerificaFirma.d';
import { FormatoFile } from './formatoFile.d';
import { TipoContenutoDocumento } from './tipoContenutoDocumento.d';
import { AnteprimaContenutoDocumento } from './anteprimaContenutoDocumento.d';
import { InfoVerificaFirma } from './infoVerificaFirma.d';
import { InfoFirmaFea } from './infoFirmaFea.d';


/**
 * Model che contiene i campi relativi al contenuto dei documenti
 */
export interface ContenutoDocumento { 
    nomeFile?: string;
    dimensione?: number;
    tipo?: TipoContenutoDocumento;
    tipoFirma?: TipoFirma;
    formatoFile?: FormatoFile;
    id?: number;
    dataVerificaFirma?: string;
    infoVerificaFirme?: Array<InfoVerificaFirma>;
    esitoVerificaFirma?: EsitoVerificaFirma;
    dtCancellazione?: string;
    dtInserimento?: string;
    anteprime?: Array<AnteprimaContenutoDocumento>;
    shaFile?: string;
    tipoContenutoFirmato?: TipoContenutoFirmato;
    infoFirmaFea?: InfoFirmaFea;
}

