/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * documento
 * API per la gestione documenti da parte dei fruitori esterni
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EsitoCreazioneDocumentoLinkFruitore } from './esitoCreazioneDocumentoLinkFruitore.d';


export interface EsitoCreazioneDocumentiLinkFruitore { 
    esiti?: Array<EsitoCreazioneDocumentoLinkFruitore>;
}

