/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * acta.v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VoceTitolarioActa { 
    id?: string;
    dbKey?: string;
    changeToken?: string;
    dataInizio?: string;
    dataFine?: string;
    codice?: string;
    descrizione?: string;
    stato?: string;
    presenzaFascTemp?: boolean;
    dataAggiornamento?: string;
    idProvvedimentoAutorizzatList?: Array<number>;
    descrBreve?: string;
    presenzaFascicoloRealeAnnualeNV?: boolean;
    insertSottoVociGestCont?: boolean;
    presenzaSerieDoc?: boolean;
    paroleChiave?: string;
    presenzaFascStand?: boolean;
    conservazioneGenerale?: number;
    presenzaFascRealeLiberoNV?: boolean;
    indiceClassificazioneEstesa?: string;
    presenzaSerieDoss?: boolean;
    presenzaFascRealeEreditatoNV?: boolean;
    presenzaFascRealeContinuoNV?: boolean;
    conservazioneCorrente?: number;
}

