/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * proxy-locale
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StiloAllegatoRequest } from './stiloAllegatoRequest.d';


/**
 * AddUdRequest
 */
export interface AddUdRequest { 
    codApplicazione?: string;
    istanzaApplicazione?: string;
    userName?: string;
    password?: string;
    xml?: string;
    hash?: string;
    allegati?: Array<StiloAllegatoRequest>;
}

