/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * notifications
 * api per cosmo notifica 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modello del servizio di notifica
 */
export interface CreaNotificaRequest { 
    idFruitore?: number;
    idPratica?: number;
    messaggio: string;
    arrivo?: string;
    scadenza?: string;
    utentiDestinatari?: Array<string>;
    gruppiDestinatari?: Array<string>;
    classe?: string;
    push?: boolean;
    codiceIpaEnte?: string;
    tipoNotifica?: string;
    evento?: string;
    url?: string;
    descrizione_url?: string;
}

