/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * notifications
 * api per cosmo notifica 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Fruitore } from './fruitore.d';
import { Pratica } from './pratica.d';


/**
 * modello del servizio di notifica
 */
export interface Notifica { 
    id?: number;
    fruitore?: Fruitore;
    descrizione?: string;
    arrivo?: string;
    scadenza?: string;
    lettura?: string;
    codiceFiscale?: string;
    pratica?: Pratica;
    destinatari?: Array<string>;
    url?: string;
    urlDescrizione?: string;
}

