/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package it.csi.cosmo.cosmonotifications.util.logger;

/**
 * Enumerazione contenente tutte le categorie da indicare nei log
 */
public enum LogCategory {

  //@formatter:off
  COSMONOTIFICATIONS_INFINISPAN_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".cluster"),
  COSMONOTIFICATIONS_MESSAGING_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".messaging"),
  COSMONOTIFICATIONS_WEBSOCKET_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".websocket"),
  COSMONOTIFICATIONS_BUSINESS_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".business"),
  COSMONOTIFICATIONS_MAIL_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".mail"),
  COSMONOTIFICATIONS_FILESHARE_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".fileshare"),
  COSMONOTIFICATIONS_DISCOVERY_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".discovery"),
  COSMONOTIFICATIONS_SECURITY_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".security"),
  COSMONOTIFICATIONS_FILTER_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".filter"),
  COSMONOTIFICATIONS_REST_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".rest"),
  COSMONOTIFICATIONS_UTIL_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".util"),
  COSMONOTIFICATIONS_PROXY_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY +  ".proxy"),
  COSMONOTIFICATIONS_AUDIT_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY +  ".audit"),
  COSMONOTIFICATIONS_BATCH_LOG_CATEGORY(LoggerConstants.COSMONOTIFICATIONS_ROOT_LOG_CATEGORY + ".batch");
  //@formatter:on

  private String category;

  private LogCategory(String category) {
    this.category = category;
  }

  public String getCategory() {
    return category;
  }
}
