/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness
 * Api per cosmobusiness
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FirmaDocumentoFruitore } from './firmaDocumentoFruitore.d';
import { TipoDocumentoFruitore } from './tipoDocumentoFruitore.d';
import { StatoDocumentoFruitore } from './statoDocumentoFruitore.d';
import { ArchiviazioneDocumentoFruitore } from './archiviazioneDocumentoFruitore.d';


/**
 * 
 */
export interface DocumentoFruitore { 
    id: string;
    idPadre?: string;
    nomeFile?: string;
    dimensione?: number;
    titolo?: string;
    descrizione?: string;
    autore?: string;
    mimeType?: string;
    firme?: Array<FirmaDocumentoFruitore>;
    archiviazione?: ArchiviazioneDocumentoFruitore;
    refURL?: string;
    tipo?: TipoDocumentoFruitore;
    stato: StatoDocumentoFruitore;
    idCosmo?: string;
}

