/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness callback delibere
 * Api per la gestione dei callback per creazione e aggiornamento delle delibere
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modello per una delibera
 */
export interface RegaxDelibere { 
    del_codice: number;
    del_numero?: number;
    contdel_contesto: number;
    progressivo?: number;
    del_dataapprovazione?: string;
    del_oggetto: string;
}

