/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness callback delibere
 * Api per la gestione dei callback per creazione e aggiornamento delle delibere
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modello per una RegaxSedeLegalAassociazione
 */
export interface RegaxSedelegaleassociazione { 
    ass_cod?: number;
    sedelegale_presso?: string;
    sedelegale_indirizzo?: string;
    sedelegale_cap?: string;
    sedelegale_comune?: string;
    sedelegale_provincia?: string;
    sedelegale_numfax?: string;
    sedelegale_numtel1?: string;
    sedelegale_numtel2?: string;
    sedelegale_data?: string;
    sedelegale_email1?: string;
    sedelegale_sitoweb1?: string;
}

