/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness callback delibere
 * Api per la gestione dei callback per creazione e aggiornamento delle delibere
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modello per una RegaxComunicazione
 */
export interface RegaxComunicazioni { 
    ass_cod?: number;
    comunicazioni_presso?: string;
    comunicazioni_sedime?: number;
    comunicazioni_indirizzo?: string;
    comunicazioni_numcivico?: number;
    comunicazioni_bis?: number;
    comunicazioni_interno?: number;
    comunicazioni_lettera?: string;
    comunicazioni_cap?: string;
    comunicazioni_circoscriz?: string;
    comunicazioni_comune?: string;
    comunicazioni_provincia?: string;
    comunicazioni_numfax?: string;
    comunicazioni_numtel1?: string;
    comunicazioni_intstatario1?: string;
    comunicazioni_numtel2?: string;
    comunicazioni_intstatario2?: string;
    comunicazioni_numtel3?: string;
    comunicazioni_data?: string;
    comunicazioni_email1?: string;
}

