/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness callback delibere
 * Api per la gestione dei callback per creazione e aggiornamento delle delibere
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modello per una RegaxSezioneLocaleAssociazione
 */
export interface RegaxSezionelocaleassociazione { 
    ass_cod?: number;
    sezlocale_presso?: string;
    sezlocale_sedime?: number;
    sezlocale_indirizzo?: string;
    sezlocale_numcivico?: number;
    sezlocale_bis?: number;
    sezlocale_interno?: number;
    sezlocale_lettera?: string;
    sezlocale_cap?: string;
    sezlocale_circoscriz?: number;
    sezlocale_comune?: string;
    sezlocale_provincia?: string;
    sezlocale_numfax?: string;
    sezlocale_numtel1?: string;
    sezlocale_numtel2?: string;
    sezlocale_data?: string;
    sezlocale_email2?: string;
    sezlocale_sitoweb2?: string;
}

