/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness callback delibere
 * Api per la gestione dei callback per creazione e aggiornamento delle delibere
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modello per una RegaxAssociazione
 */
export interface RegaxAssociazione { 
    ass_cod?: number;
    ass_denominazione?: string;
    ass_etichetta?: string;
    ass_codicefiscale?: string;
    ass_partitaiva?: string;
    ass_datainserimento?: string;
    ass_dataarrivo?: string;
    statoass_codice?: number;
    ass_numeroaderenti?: number;
    prot_codice?: number;
}

