/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness callback delibere
 * Api per la gestione dei callback per creazione e aggiornamento delle delibere
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * modello per una RegaxSedeOperativa
 */
export interface RegaxSedeoperativa { 
    ass_cod?: number;
    sedeoperativa_presso?: string;
    sedeoperativa_sedime?: number;
    sedeoperativa_indirizzo?: string;
    sedeoperativa_numcivico?: number;
    sedeoperativa_bis?: number;
    sedeoperativa_interno?: string;
    sedeoperativa_lettera?: string;
    sedeoperativa_cap?: string;
    sedeoperativa_circoscriz?: number;
    sedeoperativa_comune?: string;
    sedeoperativa_provincia?: string;
    sedeoperativa_numfax?: string;
    sedeoperativa_numtel1?: string;
    sedeoperativa_numtel2?: string;
    sedeoperativa_email1?: string;
    sedeoperativa_sitoweb1?: string;
    sedeoperativa_data?: string;
}

