/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness
 * Api per cosmobusiness
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampiTecnici } from './campiTecnici.d';


export interface RiferimentoAttivita { 
    id?: number;
    nome?: string;
    descrizione?: string;
    dataCancellazione?: string;
    formKey?: string;
    campiTecnici?: CampiTecnici;
    esterna?: boolean;
}

