/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * cosmobusiness
 * Api per cosmobusiness
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VariabileProcesso } from './variabileProcesso.d';


/**
 * Response che contiene l\'elenco delle variabili del processo insieme alle informazioni di base sull\'istanza
 */
export interface VariabiliProcessoResponse { 
    processInstanceId?: string;
    variabili?: Array<VariabileProcesso>;
}

