/*
 * Copyright CSI-Piemonte - 2023
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/**
 * Pratiche
 * API per la gestione pratiche 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TabsDettaglio } from './tabsDettaglio.d';
import { AggiornaTipoPraticaDocumentoRequest } from './aggiornaTipoPraticaDocumentoRequest.d';
import { AggiornaTipoPraticaStatoRequest } from './aggiornaTipoPraticaStatoRequest.d';
import { AggiornaTipoPraticaTrasformazioneDatiRequest } from './aggiornaTipoPraticaTrasformazioneDatiRequest.d';


/**
 * Model che descrive la richiesta di aggiornamento di un tipo pratica
 */
export interface AggiornaTipoPraticaRequest { 
    descrizione?: string;
    processDefinitionKey?: string;
    caseDefinitionKey?: string;
    codiceApplicazioneStardas?: string;
    idEnte: number;
    stati?: Array<AggiornaTipoPraticaStatoRequest>;
    tipiDocumento?: Array<AggiornaTipoPraticaDocumentoRequest>;
    creabileDaInterfaccia: boolean;
    creabileDaServizio: boolean;
    trasformazioni?: Array<AggiornaTipoPraticaTrasformazioneDatiRequest>;
    codiceCustomForm?: string;
    responsabileTrattamentoStardas?: string;
    overrideResponsabileTrattamento?: boolean;
    annullabile?: boolean;
    condivisibile?: boolean;
    assegnabile?: boolean;
    tabsDettaglio?: Array<TabsDettaglio>;
    ordine?: number;
    codiceFruitoreStardas?: string;
    overrideFruitoreDefault?: boolean;
    idGruppoCreatore?: number;
    idGruppoSupervisore?: number;
    registrazioneStilo?: string;
    tipoUnitaDocumentariaStilo?: string;
    immagine?: string;
    codiceEnteCertificatore?: string;
    codiceTipoCredenziale?: string;
    codiceTipoOtp?: string;
    codiceProfiloFEQ?: string;
    codiceSceltaMarcaTemporale?: string;
}

